"""
Base Report Generator (Abstract)
HTML 报告生成器基类

提供 HTML 报告的基础框架（头部、样式、布局），
子类需实现 _generate_sections() 填充环境特定内容。
"""

import os
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Dict, List, Optional


class BaseReportGenerator(ABC):
	"""HTML 报告生成器基类

	子类需实现 _generate_sections() 方法，返回 HTML 片段列表。

	Args:
		env_name: 环境名称
		accent_color: 主题强调色 (hex)
	"""

	def __init__(
		self,
		env_name: str = "PowerZoo",
		accent_color: str = "#4F46E5",
	):
		self.env_name = env_name
		self.accent_color = accent_color

	def generate_report(
		self,
		snapshots: List[Dict[str, Any]],
		metadata: Optional[Dict[str, Any]] = None,
		output_path: Optional[str] = None,
	) -> str:
		"""生成完整 HTML 报告

		Args:
			snapshots: 快照列表
			metadata: 报告元数据
			output_path: 可选输出文件路径

		Returns:
			HTML 字符串
		"""
		metadata = metadata or {}
		sections = self._generate_sections(snapshots, metadata)
		html = self._assemble_html(sections, metadata)

		if output_path is not None:
			os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
			with open(output_path, "w", encoding="utf-8") as f:
				f.write(html)

		return html

	@abstractmethod
	def _generate_sections(
		self,
		snapshots: List[Dict[str, Any]],
		metadata: Dict[str, Any],
	) -> List[str]:
		"""生成报告各 section 的 HTML 片段

		Args:
			snapshots: 快照列表
			metadata: 报告元数据

		Returns:
			HTML 片段列表
		"""
		...

	def _assemble_html(
		self,
		sections: List[str],
		metadata: Dict[str, Any],
	) -> str:
		"""组装完整 HTML 文档

		Args:
			sections: HTML 片段列表
			metadata: 报告元数据

		Returns:
			完整 HTML 字符串
		"""
		timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
		algo = metadata.get("algorithm", "Unknown")
		seed = metadata.get("seed", "-")

		body_content = "\n".join(sections)

		return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PowerZoo {self.env_name} - Episode Report</title>
<style>
body {{
	font-family: Inter, -apple-system, sans-serif;
	background: #1a1a2e;
	color: #e0e0e0;
	margin: 0;
	padding: 20px;
	line-height: 1.6;
}}
.container {{
	max-width: 1200px;
	margin: 0 auto;
}}
h1 {{
	color: {self.accent_color};
	border-bottom: 2px solid {self.accent_color};
	padding-bottom: 10px;
}}
h2 {{
	color: {self.accent_color};
	margin-top: 30px;
}}
.meta-bar {{
	display: flex;
	gap: 20px;
	background: #16213e;
	padding: 12px 20px;
	border-radius: 8px;
	margin-bottom: 20px;
	flex-wrap: wrap;
}}
.meta-item {{
	font-size: 0.9em;
}}
.meta-label {{
	color: #a0a0a0;
}}
.meta-value {{
	color: #e0e0e0;
	font-weight: 600;
}}
table {{
	width: 100%;
	border-collapse: collapse;
	margin: 15px 0;
}}
th, td {{
	padding: 8px 12px;
	text-align: left;
	border-bottom: 1px solid #2a2a4a;
}}
th {{
	background: #16213e;
	color: {self.accent_color};
}}
tr:hover {{
	background: rgba(79, 70, 229, 0.1);
}}
.section {{
	background: #16213e;
	border-radius: 8px;
	padding: 20px;
	margin: 15px 0;
}}
.chart-container {{
	background: #0f0f23;
	border-radius: 6px;
	padding: 10px;
	margin: 10px 0;
}}
.footer {{
	text-align: center;
	color: #a0a0a0;
	font-size: 0.85em;
	margin-top: 40px;
	padding-top: 20px;
	border-top: 1px solid #2a2a4a;
}}
</style>
</head>
<body>
<div class="container">
<h1>PowerZoo {self.env_name} - Episode Report</h1>
<div class="meta-bar">
	<div class="meta-item">
		<span class="meta-label">Algorithm: </span>
		<span class="meta-value">{algo}</span>
	</div>
	<div class="meta-item">
		<span class="meta-label">Seed: </span>
		<span class="meta-value">{seed}</span>
	</div>
	<div class="meta-item">
		<span class="meta-label">Generated: </span>
		<span class="meta-value">{timestamp}</span>
	</div>
</div>

{body_content}

<div class="footer">
	Generated by PowerZoo Render System | {timestamp}
</div>
</div>
</body>
</html>"""
